name: cmake_windows.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up MSVC compiler
      uses: ilammy/msvc-dev-cmd@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pandas

    - name: Create Build Directory
      run: mkdir build && cd build

    - name: Configure CMake project
      run: cmake -S . -B build -G "Visual Studio 17 2022"
      working-directory: ${{github.workspace}}

    - name: Build project
      run: cmake --build build --config Release
      working-directory: ${{github.workspace}}

    - name: Run pytest
      run: pytest --color=yes --verbose -s
      working-directory: ${{github.workspace}}/tests